USE [master]
GO
/****** Object:  Database [ClinicDb]    Script Date: 9/16/2023 5:45:56 PM ******/
CREATE DATABASE [ClinicDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClinicDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ClinicDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ClinicDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ClinicDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ClinicDb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClinicDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ClinicDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ClinicDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ClinicDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ClinicDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ClinicDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [ClinicDb] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ClinicDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ClinicDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ClinicDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ClinicDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ClinicDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ClinicDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ClinicDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ClinicDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ClinicDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ClinicDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ClinicDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ClinicDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ClinicDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ClinicDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ClinicDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ClinicDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ClinicDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ClinicDb] SET  MULTI_USER 
GO
ALTER DATABASE [ClinicDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ClinicDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ClinicDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ClinicDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ClinicDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ClinicDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ClinicDb] SET QUERY_STORE = OFF
GO
USE [ClinicDb]
GO
/****** Object:  Table [dbo].[DoctorWorkDays]    Script Date: 9/16/2023 5:45:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DoctorWorkDays](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DayId] [int] NULL,
	[DoctorID] [int] NULL,
 CONSTRAINT [PK_DoctorWorkDays] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBLClinic]    Script Date: 9/16/2023 5:45:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLClinic](
	[ClinicID] [int] IDENTITY(1,1) NOT NULL,
	[ClinicName] [varchar](255) NULL,
	[ClinicAddress] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ClinicID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBLDoctors]    Script Date: 9/16/2023 5:45:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO 
CREATE TABLE [dbo].[TBLDoctors](
	[DoctorID] [int] IDENTITY(1,1) NOT NULL,
	[DoctorName] [varchar](255) NULL,
	[About] [nvarchar](500) NULL,
	[ClinicID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[DoctorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBLDoctorSchedule]    Script Date: 9/16/2023 5:45:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBLDoctorSchedule](
	[ScheduleID] [int] IDENTITY(1,1) NOT NULL,
	[DoctorID] [int] NOT NULL,
	[DayOfWeek] [int] NOT NULL,
	[StartTime] [time](7) NULL,
	[EndTime] [time](7) NULL,
	[PatientName] [nvarchar](255) NULL,
	[PatientAge] [int] NULL,
	[Date] [date] NULL,
 CONSTRAINT [PK__DoctorSc__9C8A5B696B9BD50B] PRIMARY KEY CLUSTERED 
(
	[ScheduleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WeekDays]    Script Date: 9/16/2023 5:45:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WeekDays](
	[Id] [int] NOT NULL,
	[Day] [nvarchar](100) NULL,
 CONSTRAINT [PK_WeekDays] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DoctorWorkDays]  WITH CHECK ADD  CONSTRAINT [FK_DoctorWorkDays_TBLDoctors] FOREIGN KEY([DoctorID])
REFERENCES [dbo].[TBLDoctors] ([DoctorID])
GO
ALTER TABLE [dbo].[DoctorWorkDays] CHECK CONSTRAINT [FK_DoctorWorkDays_TBLDoctors]
GO
ALTER TABLE [dbo].[DoctorWorkDays]  WITH CHECK ADD  CONSTRAINT [FK_DoctorWorkDays_WeekDays] FOREIGN KEY([DayId])
REFERENCES [dbo].[WeekDays] ([Id])
GO
ALTER TABLE [dbo].[DoctorWorkDays] CHECK CONSTRAINT [FK_DoctorWorkDays_WeekDays]
GO
ALTER TABLE [dbo].[TBLDoctors]  WITH CHECK ADD  CONSTRAINT [FK_ClinicID] FOREIGN KEY([ClinicID])
REFERENCES [dbo].[TBLClinic] ([ClinicID])
GO
ALTER TABLE [dbo].[TBLDoctors] CHECK CONSTRAINT [FK_ClinicID]
GO
ALTER TABLE [dbo].[TBLDoctorSchedule]  WITH CHECK ADD  CONSTRAINT [FK_TBLDoctorSchedule_WeekDays] FOREIGN KEY([DayOfWeek])
REFERENCES [dbo].[WeekDays] ([Id])
GO
ALTER TABLE [dbo].[TBLDoctorSchedule] CHECK CONSTRAINT [FK_TBLDoctorSchedule_WeekDays]
GO
ALTER TABLE [dbo].[TBLDoctorSchedule]  WITH CHECK ADD  CONSTRAINT [ForiegnKey_DoctorId] FOREIGN KEY([DoctorID])
REFERENCES [dbo].[TBLDoctors] ([DoctorID])
GO
ALTER TABLE [dbo].[TBLDoctorSchedule] CHECK CONSTRAINT [ForiegnKey_DoctorId]
GO
USE [master]
GO
ALTER DATABASE [ClinicDb] SET  READ_WRITE 
GO
